language: c

compiler:
  - clang

before_install:
  - if [ "$CC" == "clang" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

install:
  - if [ "$CC" == "clang" ]; then sudo apt-get install -qq clang-3.5; fi
  - if [ "$CC" == "clang" ]; then export CC="clang-3.5"; fi

script:
  - make
  - ./cards
